name: Build Amd64 Image
on:
  push:
    branches:
      - build
jobs:
  build:
      runs-on: ubuntu-latest
      name: Build image job
      steps:
          - name: Checkout master
            uses: actions/checkout@master
          - name: ACR login
            env:
              DOCKER_PWD: ${{ secrets.ACR_PWD }}
              DOCKER_USER: ${{ secrets.ACR_USER }}
            run: |
              echo "${DOCKER_PWD}" | docker login --username ${DOCKER_USER} --password-stdin  registry.cn-hangzhou.aliyuncs.com
              echo "abc@12311" | docker login --username yuxff --password-stdin  
          - name: docker buildx
            id: buildx
            uses: crazy-max/ghaction-docker-buildx@v1
            with:
              buildx-version: latest
          - name: build dockerfile with push
            env: 
              DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            run: |
          - name: build dockerfile with push
            env:
              DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            run: |
              for image in $(<image.list);do 
                if [[ $image =~ ^\#.* ]];then   
                  continue;
                fi
                echo $image
                docker pull $image
                docker tag $image registry.cn-hangzhou.aliyuncs.com/yuxf/${image##*/} || continue
                docker push registry.cn-hangzhou.aliyuncs.com/yuxf/${image##*/} || continue
              done
